### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by TobiasPruef** [GabeWeiss/GoogleIoTCoreApp#19]
Hi, 
i’m a Student an I’m dealing with the google cloud. 
I’ve got a Microchip IoT-Board and I would like to show the telemetry data of the board over the time. 
I would like to watch the data as a real time chart. 
I saw your Video on Youtube:  https://www.youtube.com/watch?v=RYaprBSDy8A. Is this the easiest way to view telemtetry data? 
Or is this just a demonstration of your tools? Maybe you got a toolbox to create some charts. 
I’ve created my own Project, using IoT-Core und Pub/Sub. I’m able to watch the mqtt messages incoming. But now I would like to create some charts. Do I need to use the way like you did in your video? 
Iot-Core -> Pub/Sub -> Cloud Functions -> Cloud Firebase -> Anglular 
I know it is possible to use instead of Cloud Functions, Cloud Dataproc or Cloud Dataflow. 
But is it really necessary to use five tools to view telemetry data? Is there no tool? 

Could you help me? 

With best regards 

Tobias

**Comment by GabeWeiss** [comment]
Hi Tobias, Sorry for the delay, it's been a messy time. 

There's no out of the box tools to view the telemetry, no unfortunately. To look at the raw telemetry for confirming it's coming in, adding a subscription onto the Pub/Sub topic, and manually pulling the messages yourself, either using gcloud, or the console, is a way to just see them to confirm they're working.

To look at them in like, a chart format, as long as you don't need them in real time, probably the EASIEST way to do it, would be to create a Dataflow pipeline using the template, and go Pub/Sub -> BigQuery. And then use Data Studio to create the chart which has a template for using a BigQuery table as the data source.

That way doesn't require any coding at all to see the telemetry.
