### ISSUE TITLE
i wanna send data from google cloud subpub function to firebase realtime database?? your code didn't work for me..any help ?

### ISSUE THREAD

**Issue by hanadjerbi1** [GabeWeiss/GoogleIoTCoreApp#6]

**Comment by GabeWeiss** [comment]
What error messages do you get? Did you confirm the Cloud Function is firing at all? (I usually print out to log, and check StackDriver to see if your logging messages are being written)

**Comment by hanadjerbi1** [comment]
well first..did you use the realtime database firebase fromm google cloud platform to store in the firebase or what ?

**Comment by GabeWeiss** [comment]
We used Firestore, which is an option when setting up the real-time DB in the firebase console. It asks you if you want Firebase, or Firestore. The SDK/API is different for the two, so our code will not work with Firebase RTDB, has to be Firestore.
